### PR TITLE
Fix truncated output on Node v6

### PR DESCRIPTION
**Pull request by feross**
Closes https://github.com/feross/standard/issues/519

### CODE REVIEW

**Comment by feross** [comment]
4.0.2

**Comment by 75lb** [comment]
confirmed.. cheers brother 👍

**Comment by Flet** [comment]
Excellent! Thanks for taking care of this!

**Comment by feross** [comment]
Should be noted that node v0.10 doesn't support `process.exitCode`, so `standard-engine` will always return exit code 0 on that version of node. I don't think it's worth worrying about it too much. No one puts *only v0.10* in their Travis config / CI these days.

**Comment by dcousens** [comment]
@feross maybe enforce that then by throwing on `0.10`?

**Comment by feross** [comment]
@dcousens I don't think it's worth the effort to special case it, do you? The warnings will still get output.

**Comment by Flet** [comment]
The most effort I would put into it is to add an `engines` entry in `package.json` and maybe a note in the readme :smile:

**Pull request merged**
