### PR TITLE
BREAKING: User must pass eslint dependency in as option

### LINKED ISSUE #45: Remove eslint
*From https://github.com/Flet/standard-engine/pull/43#issuecomment-167224706:*

I think we should remove eslint from this package and make the user pass in whatever version they want. That makes more sense anyway, since the user is specifying the rules, and those will be dependent on the eslint version.

This is a breaking change.

### PR DESCRIPTION
**Pull request by feross**
Fix #45

### CODE REVIEW

**Comment by Flet** [comment]
:+1: 

Are there any other breaking changes we want to consider to `standard-engine` before publishing?

**Comment by feross** [comment]
Published this as 3.0.0, in preparation of standard 6. :)

**Comment by dcousens** [comment]
@feross is there a roadmap / issue where we can discuss all the upcoming changes for S6?

**Comment by feross** [comment]
There's a tag on the standard repo called "v6". I'll make an issue and propose a release.

**Pull request merged**
