### PR TITLE
Add a link to strict-standard

### PR DESCRIPTION
**Pull request by denis-sokolov**
I don't know what's your policy on adding these links are, but the Readme suggested to be bold about it. :)

### CODE REVIEW

**Comment by dcousens** [comment]
Out of interest,  what differentiates this from `standard` actually?
It mentions more error catching,  but no stylistic differences?

**Comment by denis-sokolov** [comment]
@dcousens, yep. I wanted to use `standard`, but I really disliked giving up most error catching, and the default `standard` eslint configuration is pretty lax.

**Comment by dcousens** [comment]
Any particular example?

**Comment by denis-sokolov** [comment]
There's [the list of all rules](https://github.com/denis-sokolov/strict-standard-config/blob/master/src/index.js) that are enabled in strict-standard. I assume you are familiar with eslint.

**Pull request merged**
